name: Exercise 2 Workflow

on:
  push:
   branches: [main]
        
env:
    ARTIFACT_VAR: "Meu Arquivo"

jobs:
  build: 
    runs-on: ubuntu-latest 

    steps:
    - name: Step1
      uses: actions/checkout@v2

    - name: Step2
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{ env.ARTIFACT_VAR }}
        path: .
        if-no-files-found: error
