# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1: 
    name: First job
    runs-on: ubuntu-latest 
    steps:
      - name: Step
        run: date

  job2: 
      name: Second job
      runs-on: windows-latest 
      steps:
          - name: Step
            run: date
  job3:
      name: Third job
      runs-on: macOS-latest
      steps: 
          - name: Step
            run: date
  job4:
      name: Final job
      runs-on: ubuntu-latest
      needs: [job1, job2, job3]
      steps: 
          - name: Step
            run: date
